### ISSUE TITLE
`CheckBox` in `MenuItem.Icon` doesn't display correctly

### ISSUE THREAD

**Issue by IsaacMarovitz** [amwx/FluentAvalonia#367] opened 2023-05-16 15:58 UTC
**Describe the bug**
If you use a CheckBox in a MenuItem.Icon, the resulting CheckBox will be too small and off-center.

```csharp
<MenuItem
    Command="{Binding ToggleStartGamesInFullscreen}"
    Header="{locale:Locale MenuBarOptionsStartGamesInFullscreen}">
    <MenuItem.Icon>
        <CheckBox MinWidth="{DynamicResource CheckBoxSize}"
                  MinHeight="{DynamicResource CheckBoxSize}"
                  IsChecked="{Binding StartGamesInFullscreen, Mode=TwoWay}"/>
    </MenuItem.Icon>
</MenuItem>
```
MinWidth and MinHeight do not seem to have the desired changes; excluding them or changing their value doesn't solve the problem. Worked in Ava 10.

**Screenshots:**
<img width="478" alt="Screenshot 2023-05-16 at 11 57 17" src="https://github.com/amwx/FluentAvalonia/assets/42140194/f2a14930-94ad-4f7a-ba68-a292655e26b0">

`Icon` `CheckBox` shown in top-left, expected CheckBox size shown in bottom right.

**Desktop/Platform:**
 - OS: Windows 11/macOS
 - FluentAvalonia Version: 2.0.0-preview8
 - Avalonia Version: 11.0.0-preview8

**Comment by amwx** [comment] 2023-05-24 03:13
It looks like the padding around the ContentPresenter for CheckBox is reserving space to the right of the check area which is messing with the scaling in the Viewbox of MenuItem's template (the Viewbox is why you can't change the size yourself). Probably best to use a special styling class to just hide the ContentPresenter in CheckBoxes used within MenuItem.

Closing as by-design.

**Closed by amwx** 2023-05-24 03:13 UTC
Labels: bug

**Comment by IsaacMarovitz** [comment] 2023-05-29 13:56
> Closing as by-design.

Disabling the ContentPresenter doesn't seem to make any significant difference. I checked and the ones that are being displayed correctly are just part of the HeaderPresenter ie not the IconPresenter at all.

**Comment by amwx** [comment] 2023-05-29 17:00
You might be better off waiting until https://github.com/AvaloniaUI/Avalonia/pull/11441 is ready which won't require a checkbox for toggle menu items. 


> Another slightly unrelated issue, but the shortcut in the screenshot `F11` is getting pushed to the side by a Chevron icon, even though that menu item has no children.

This is probably because WPF menus (which Avalonia mimics) uses Grid.SharedSizeScope for menu items and the InputGesture text and the chevron are two different grid columns. This too, is by design.

**Comment by Alexbeerses** [comment] 2024-12-25 11:18
CheckBox in menuItem icon is stiil clipped in Avalonia 11.2.2.
![image](https://github.com/user-attachments/assets/b9619c0c-4860-48e4-bc5c-59031d82aacf)
