### ISSUE TITLE
TaskDialog Default Button

### ISSUE THREAD

**Issue by mysteryx93** [amwx/FluentAvalonia#168] opened 2022-06-16 19:15 UTC
TaskDialog provides a lot of useful extra features compared to ContentDialog, but there's one notable feature missing:

DefaultButton and CancelButton

Any chance to add that feature?

**Comment by amwx** [comment] 2022-06-23 22:42
`DefaultButton` is implemented. You can't use it if using `TaskDialogButton.OKButton` or any of the other built-in buttons as those are kept simplistic by design. Instead define a `TaskDialogButton` and set the `IsDefault` property to true (see below). 
`CancelButton` is handled implicitly by the `TaskDialog` listening for the Escape key and closing the dialog with `TaskDialogStandardResult.None`

```C#
var td = new TaskDialog
{
    XamlRoot = this,
    Content = "Default Button Test",
    Buttons =
    {
        new TaskDialogButton
        {
            Text = "OK",
            IsDefault = true,
            DialogResult = TaskDialogStandardResult.OK
        },
        new TaskDialogButton
        {
            Text = "Cancel"
        }
    }
};
```

**Closed by amwx** 2022-06-23 22:42 UTC
Labels: enhancement
