### ISSUE TITLE
Issue running latest sample

### ISSUE THREAD

**Issue by banditpig** [amwx/FluentAvalonia#556] opened 2024-04-25 11:44 UTC
I've cloned the repo and I'm running on Mac M1 Ventura and running the desktop samples I get 
Unhandled exception. System.InvalidOperationException: Deserialization of init-only properties is currently not supported in source generation mode.
   at FAControlsGallery.ViewModels.FAControlsJsonSerializerContext.<>c.<PageBaseViewModelPropInit>b__34_3(Object obj, String value) in /Users/mikehoughton/RiderProjects/FluentAvalonia/samples/FAControlsGallery/System.Text.Json.SourceGeneration/System.Text.Json.SourceGeneration.JsonSourceGenerator/FAControlsJsonSerializerContext.PageBaseViewModel.g.cs:line 85
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at FAControlsGallery.ViewModels.CoreControlsPageViewModel..ctor(String coreControlsJson) in /Users/mikehoughton/RiderProjects/FluentAvalonia/samples/FAControlsGallery/ViewModels/CoreControlsPageViewModel.cs:line 12
   at FAControlsGallery.Views.MainView.InitializeNavigationPages() in /Users/mikehoughton/RiderProjects/FluentAvalonia/samples/FAControlsGallery/Views/MainView.axaml.cs:line 113
   at FAControlsGallery.Views.MainView.<OnAttachedToVisualTree>b__1_0() in /Users/mikehoughton/RiderProjects/FluentAvalonia/samples/FAControlsGallery/Views/MainView.axaml.cs:line 76
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at FluentAvalonia.UI.Windowing.SplashScreenContext.RunJobs() in /Users/mikehoughton/RiderProjects/FluentAvalonia/src/FluentAvalonia/UI/Windowing/AppWindow/SplashScreenContext.cs:line 31
   at FluentAvalonia.UI.Windowing.AppWindow.OnOpened(EventArgs e) in /Users/mikehoughton/RiderProjects/FluentAvalonia/src/FluentAvalonia/UI/Windowing/AppWindow/AppWindow.cs:line 167
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.RunJobs(Nullable`1 priority, CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.RunJobs(Nullable`1 priority)
   at Avalonia.Native.WindowBaseImpl.WindowBaseEvents.Avalonia.Native.Interop.IAvnWindowBaseEvents.RunRenderPriorityJobs()
   at Avalonia.Native.Interop.Impl.__MicroComIAvnWindowBaseEventsVTable.RunRenderPriorityJobs(Void* this)
--- End of stack trace from previous location ---
   at Avalonia.Native.DispatcherImpl.RunLoop(CancellationToken token)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at FAControlsGallery.Desktop.Program.Main(String[] args) in /Users/mikehoughton/RiderProjects/FluentAvalonia/samples/FAControlsGallery.Desktop/Program.cs:line 12

**Comment by imJack6** [comment] 2024-04-25 14:18
same

**Comment by timunie** [comment] 2024-04-25 14:23
please try https://github.com/amwx/FluentAvalonia/pull/541 instead

**Comment by AstroLuminous** [comment] 2024-04-26 09:44
System.InvalidOperationException
  HResult=0x80131509
  Message=Deserialization of init-only properties is currently not supported in source generation mode.
  Source=FAControlsGallery
  StackTrace:
   在 FAControlsGallery.ViewModels.FAControlsJsonSerializerContext.<>c.<PageBaseViewModelPropInit>b__34_3(Object obj, String value) 在 C:\Users\float\Source\Repos\FluentAvalonia\samples\FAControlsGallery\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\FAControlsJsonSerializerContext.PageBaseViewModel.g.cs 中: 第 85 行
   在 System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   在 System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   在 System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   在 System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonTypeInfo`1 jsonTypeInfo)
   在 FAControlsGallery.ViewModels.CoreControlsPageViewModel..ctor(String coreControlsJson) 在 C:\Users\float\Source\Repos\FluentAvalonia\samples\FAControlsGallery\ViewModels\CoreControlsPageViewModel.cs 中: 第 12 行
   在 FAControlsGallery.Views.MainView.InitializeNavigationPages() 在 C:\Users\float\Source\Repos\FluentAvalonia\samples\FAControlsGallery\Views\MainView.axaml.cs 中: 第 113 行
   在 FAControlsGallery.Views.MainView.<OnAttachedToVisualTree>b__1_0() 在 C:\Users\float\Source\Repos\FluentAvalonia\samples\FAControlsGallery\Views\MainView.axaml.cs 中: 第 76 行
   在 System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

**Comment by robloo** [comment] 2024-04-27 21:05
This is a duplicate of https://github.com/amwx/FluentAvalonia/discussions/547

**Closed** 2024-04-28 01:57 UTC
Labels: bug
