### ISSUE TITLE
Using aot to publish window background is abnormal!

### ISSUE THREAD

**Issue by wj8400684** [amwx/FluentAvalonia#278] opened 2023-01-27 16:47 UTC
![image](https://user-images.githubusercontent.com/39239954/215144438-f41db3a8-9d33-4d66-89d7-26486e7e638c.png)

Like this

**Comment by timunie** [comment] 2023-01-27 19:25
how do you publish? Make sure to use `-win10-x64` or `-win7-x64` modifier. Otherwise important dll will be missing.

**Comment by amwx** [comment] 2023-01-28 03:01
Also a duplicate of #185 and #165 and Mica is done upstream anyway. But yes as noted above, make sure you target -win10 or -win7 not just -win

**Closed by amwx** 2023-01-28 03:01 UTC
Labels: enhancement

**Comment by wj8400684** [comment] 2023-01-28 12:24
![4ff47e4be60114ecdd2a710e138137a](https://user-images.githubusercontent.com/39239954/215266184-b423da5a-feba-404e-b461-ed755366ceba.png)
![0d0c63a56d1d18da71607be54a0e0da](https://user-images.githubusercontent.com/39239954/215266188-557e2292-8ec4-498d-bceb-6731fd49bd40.png)
You can see it after debugging！

**Comment by amwx** [comment] 2023-01-28 22:33
Debug != publish
Again, you have to publish your app with the `win10-x64` or `win7-x64` runtime identifier, see this command-line snippet as I don't think the publish UI in Visual Studio supports this. (You can adjust the other params as necessary)
 
`dotnet publish -c Release -o OutputDir -r win10-x64 --self-contained`

produces this:
![image](https://user-images.githubusercontent.com/40413319/215293986-ca78dd2f-adbd-46e0-86e6-e31e5a434019.png)

**Comment by wj8400684** [comment] 2023-01-29 15:00
> 
thank！
