### ISSUE TITLE
ToggleSwitch right alignment doesn't work as expected

### ISSUE THREAD

**Issue by Gigas002** [amwx/FluentAvalonia#36] opened 2021-09-17 06:45 UTC
Tested on kubuntu 21.04.

Steps to reproduce:
1. Create new app with `dotnet new avalonia.mvvm -o MyApp`
2. Add FluentAvalonia dependency ver. `1.1.2` to `.csproj` and corresponding minimal lines to `App.axaml`:

```xml
<Application xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="using:MyApp"
             x:Class="MyApp.App"
             xmlns:sty="using:FluentAvalonia.Styling"
             xmlns:ui="using:FluentAvalonia.UI.Controls"
             xmlns:uip="using:FluentAvalonia.UI.Controls.Primitives"
             >
    <Application.DataTemplates>
        <local:ViewLocator/>
    </Application.DataTemplates>

    <Application.Styles>
        <FluentTheme Mode="Dark"/>
        <sty:FluentAvaloniaTheme ControlsVersion="2" RequestedTheme="Dark" />
    </Application.Styles>
</Application>
```

3. Replace the `MainWindow.axaml`'s textbox with the following grid:

```xml
<Grid ColumnDefinitions="Auto,*,Auto">
    <ToggleSwitch Grid.Column="0" Content="Left switch"/>
    <ToggleSwitch Grid.Column="2" HorizontalAlignment="Right" Content="Right switch"/>
</Grid>
```

Results without/with FluentAvalonia:

![Default](https://user-images.githubusercontent.com/24297712/133736609-834fb66c-371b-4d0a-8a41-20c63821ce94.png)
![With FluentAvalonia](https://user-images.githubusercontent.com/24297712/133736811-0c046bce-0731-4b11-9880-d64cae59d182.png)

**Comment by amwx** [comment] 2021-09-18 21:59
Without digging too much into this, it looks like that's caused by the `MinWidth` on the `ToggleSwitch` in the template. Try setting `MinWidth = 0` and it should align properly against the right edge of the window.

**Comment by Gigas002** [comment] 2021-09-19 08:44
> 
> 
> Without digging too much into this, it looks like that's caused by the `MinWidth` on the `ToggleSwitch` in the template. Try setting `MinWidth = 0` and it should align properly against the right edge of the window.

No, that doesn't seem to fix the problem.

**Comment by amwx** [comment] 2021-09-22 22:56
Ok, so a Grid within the `ToggleSwitch` template had the `MinWidth` set on it, which was fixed upstream in WinUI a while ago. I've made the correction so that it's now applied on `ToggleSwitch` and can therefore be overridden. This will be in the next release

**Comment by amwx** [comment] 2021-09-25 01:24
v1.1.3 has be published, and you should now be able to set `MinWidth` on the `ToggleSwitch` to properly right align. If the issue still persists, feel free to reopen the issue.

**Closed by amwx** 2021-09-25 01:24 UTC
